### PR TITLE
remorts: cap HP bonus given by number of remorts

### LINKED ISSUE #22: balance: cap remorts, HP & Stamina
- We need something to be able to sweep pfiles and locate those with HP great than 7k hp, and then reset their HP to the max HP appropriate for their class.

- Should setup HP caps to be class specific:
  >Casters -  4500hp
  >Rogues -  5500hp
  >Fighters - 6500hp
Give GMs a +500hp bonus to that max.

### PR DESCRIPTION
**Pull request by lfaoro**
Signed-off-by: Leonardo Faoro <lfaoro@gmail.com>

### CODE REVIEW

**Review by Rynald4d — COMMENTED** [review]
Jubei and Vryce almost reached the 500 cap by grinding mobs. Upping it to 1000 leaves more room to grow.
I don't know how much stamina you need to get far in space, but if you give 500 to GMs this makes things worse?

**Comment by lfaoro** [comment]
Check the pfiles of Jubei, Vryce and Zi, see how much Stamina they got. I saw people with 50-60 remorts have around 500, so I thought capping it at 500 would be good.

**Comment by J00bei** [comment]
I am not a coder but this snippet is still missing  the actual bonus for remorts since you have merged them both to check if character is GM then GET_MAX_HIT(ch) = 30 + 500; you would not get any bonus at all from remorts right?

  // HP remort bonus, capped at GM level or 500 remorts.
    int remorts = REMORTS(ch);
    bool already_gm = grand_master(ch);
    if (already_gm || remorts >= 500) {
        GET_MAX_HIT(ch) = 30 + 500;

Correct me if I am wrong but the statement is saying if the person is a GM they get 500 hp.
                                 OR
If they are 500 remorts they get this same 500 hp bonus

As GM is only 32 remorts... there would be 0 bonus for actually getting 500 and setting max bonus is a lot easier than all this convoluted  additional code just look at how the previous code was made and revert it back to that. 

changing int remorts = MIN(REMORTS(ch), 1000);

**Comment by lfaoro** [comment]
Hi Jubei, no worries -- all suggestions are appreciated and welcomed.

already_gm makes sure the player has levelled through all the classes, no matter how many remorts they've had to reach mastery, could be 32 could be 50, could be 500. The 500 check is there to avoid the event a player never masters all classes, e.g. you master 5 classes then just pay for tier1 remorts until you reach 1,000 remorts and skip the gm check.

what MIN is doing is getting the lowest between 2 numbers, either your remorts or 1,000 in the case you've exemplified, still remorts are not a factor for GM, you could have 1,000 remorts and still not be GM.

you can download this branch `remorts` and submit a pull request yourself with the changes you'd like.

**Comment by Rynald4d** [comment]
See commit 9ce59614c6a416e307bf5f414c4d7932a900a6d2

**Pull request closed without merging**
